site_name: LoRa MeshCore
site_url: https://lorameshcore.pl/
nav:
  - 'Co to jest MeshCore?': 'index.md'
  - 'Jak zacząć?':
    - 'Wybór urządzenia': './jakZaczac/wyborUrzadzenia.md'
    - 'Instalacja sterowników': './jakZaczac/instalacjaSterownikow.md'
    - 'Flashowanie urzadzenia':
      - 'Heltec V3 układ ESP32': './jakZaczac/flashowanieHeltecV3.md'
      - 'Xiao nRF52840 układ nRF': './jakZaczac/flashowanieXiaoNrf.md'
    - 'Konfiguracja urządzenia z telefonu':
      - 'Android': './jakZaczac/konfiguracjaAndroid.md'
    - 'Wysyłanie wiadomości': './jakZaczac/wysylanieWiadomosci.md'
  - 'Zaawansowane':
    - 'Wymagana teoria':
      - 'Role': './zaawansowane/role.md'
      - 'Klucz publiczny i prywatny': './zaawansowane/kluczPublicznyIprywatny.md'
      - 'Routing, kanał publiczny i advert': './zaawansowane/routing.md'
      - 'Duty cycle': './zaawansowane/dutyCycle.md'
      - 'Presety': './zaawansowane/presety.md'
      - 'Rodzaje złącz antenowych': './zaawansowane/rodzajeZlaczAntenowych.md'
      - 'Dobre praktyki przy budowaniu repeaterów': './zaawansowane/jakBudowacRepeatery.md'
    - 'Repeatery':
      - 'Instalacja i pierwsza konfiguracja': './zaawansowane/repeater/instalacjaKonfiguracjaRepeatera.md'
    - 'Room Server':
      - 'Instalacja i pierwsza konfiguracja': './zaawansowane/roomServer/instalacjaKonfiguracjaRoomServer.md'
    - 'Zarządzanie urządzeniami':
      - 'Manualne wysyłanie reklam': './zaawansowane/zarzadzanie/wysylanieReklam.md'
      - 'Zdalne logowanie i opcje konfiguracyjne': './zaawansowane/zarzadzanie/zdalneLogowanie.md'
      - 'Zasady konfiguracji urządzeń': './zaawansowane/zarzadzanie/zasadyKonfiguracjiUrzadzen.md'
  - 'Słownik pojęć': 'slownikPojec.md'
  - 'FAQ':
    - 'Najczęściej zadawane pytania': './faq/faq.md'
    - 'Dlaczego nie Meshtastic': './faq/dlaczegoNieMeshtastic.md'
  - 'Przydatne linki': './przydatneLinki.md'
  - Projekt TK3K: './projektTK3K.md'
  - 'Wsparcie': './wsparcie.md'
  - 'Kontakt': './kontakt.md'
theme:
  palette:
    primary: custom
  name: material
  logo: assets/meshcore.png
  language: pl
  features:
    - search.suggest
    - search.share
    - content.tooltips
plugins:
  - search
  - glightbox:
      zoomable: true
markdown_extensions:
  - admonition
extra_css:
  - stylesheets/extra.css
repo_url: https://github.com/deFAT64/meshcore-manual-pl
copyright: >
  <a href="https://github.com/deFAT64/meshcore-manual-pl?tab=License-1-ov-file">Licencja witryny.</a> // Strona jest hostowana w serwisie radpidc.pl. <a href="https://rapiddc.pl/polityka-prywatnosci">Ich polityka prywatności.</a> // Ostatnia aktualizacja: 2025-08-17