site_name: MeshCore Manual PL
site_url: https://mydomain.org/mysite
nav:
  - 'Co to jest MeshCore?': 'index.md'
  - 'Jak zacząć?':
    - 'Wybór urządzenia': './jakZaczac/wyborUrzadzenia.md'
    - 'Instalacja sterowników': './jakZaczac/instalacjaSterownikow.md'
    - 'Flashowanie urzadzenia':
      - 'Heltec V3 układ ESP32': './jakZaczac/flashowanieHeltecV3.md'
    - 'Konfiguracja urządzenia z telefonu': './jakZaczac/konfiguracjaAndroid.md'
theme:
  name: material
  logo: assets/meshcore.png
  language: pl
  features:
    - search.suggest
    - search.share
    - content.tooltips
plugins:
  - search
  - glightbox:
      zoomable: true
markdown_extensions:
  - admonition